src/Entity/Apartment.php
<?php

namespace App\Entity;

use App\Repository\ApartmentRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ApartmentRepository::class)
 * @UniqueEntity(
 *     "address",
 *     message="Il existe déjà un appartement à cette adresse."
 * )
 */
class Apartment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThan(
     *     value = -1,
     *     message = "Un appartement ne peut être au sous-sol."
     * )
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     * @Assert\GreaterThan(
     *     value = 0,
     *     message = "Un appartement a au moins une pièce."
     * )
     */
    private $nb_room;

    /**
     * @ORM\Column(type="boolean")
     */
    private $elevator;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getNbRoom(): ?int
    {
        return $this->nb_room;
    }

    public function setNbRoom(int $nb_room): self
    {
        $this->nb_room = $nb_room;

        return $this;
    }

    public function getElevator(): ?bool
    {
        return $this->elevator;
    }

    public function setElevator(bool $elevator): self
    {
        $this->elevator = $elevator;

        return $this;
    }
}

src/Form/ApartmentType.php
<?php

namespace App\Form;

use App\Entity\Apartment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ApartmentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('address', null, [
                'label' => "Adresse"
            ])
            ->add('floor',null, [
                'label' => "Etage"
            ])
            ->add('nb_room',null, [
                'label' => "Pièce"
            ])
            ->add('elevator',null, [
                'label' => "Ascenseur"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Apartment::class,
        ]);
    }
}

src/Controller/ApartmentController.php
<?php

namespace App\Controller;

use App\Entity\Apartment;
use App\Form\ApartmentType;
use App\Repository\ApartmentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/")
 */
class ApartmentController extends AbstractController
{
    /**
     * @Route("/", name="apartment_index", methods={"GET"})
     */
    public function index(ApartmentRepository $apartmentRepository): Response
    {
        return $this->render('apartment/index.html.twig', [
            'apartments' => $apartmentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="apartment_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $apartment = new Apartment();
        $form = $this->createForm(ApartmentType::class, $apartment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($apartment);
            $entityManager->flush();

            return $this->redirectToRoute('apartment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('apartment/new.html.twig', [
            'apartment' => $apartment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="apartment_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Apartment $apartment): Response
    {
        $form = $this->createForm(ApartmentType::class, $apartment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('apartment_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('apartment/edit.html.twig', [
            'apartment' => $apartment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="apartment_delete", methods={"POST"})
     */
    public function delete(Request $request, Apartment $apartment): Response
    {
        if ($this->isCsrfTokenValid('delete'.$apartment->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($apartment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('apartment_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/apartment/_delete_form.html.twig
<form method="post" action="{{ path('apartment_delete', {'id': apartment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ apartment.id) }}">
    <button class="btn badge rounded-pill bg-danger"> Supprimer </button>
</form>

templates/apartment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un appartement{% endblock %}

{% block body %}
    <h1>Modifier un appartement</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}

    <div style="float:right">
        <a href="{{ path('apartment_index') }}"><button type="button" class="btn btn-secondary"> Retour </button></a>
        <button type="submit" class="btn btn-primary"> Modifier </button>
    </div>

    {{ form_end(form) }}

{% endblock %}

templates/apartment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Liste des appartements {% endblock %}

{% block body %}
    <h1> Liste des appartements </h1>

    <a href="{{ path('apartment_new') }}"> <button type="button" class="btn btn-secondary"> Ajouter un appartement</button></a>
    <table class="table">
        <thead>
            <tr>
                <th> </th>
                <th> </th>
                <th> </th>
            </tr>
        </thead>
        <tbody>
        {% for apartment in apartments %}
            <tr>
                <td style="vertical-align: middle"> <img src="https://picsum.photos/id/{{ apartment.id }}/50.jpg"> </td>
                <td style="vertical-align: middle">
                    {{ apartment.address }} <br>
                    <ul class="list-inline">
                        <li class="list-inline-item">Etage : {{ apartment.floor }}</li>
                        <li class="list-inline-item">Pièces : {{ apartment.nbRoom }}</li>
                        <li class="list-inline-item">
                            {% if apartment.elevator %}
                                <span style="color:blue"> ascenseur </span>
                            {% else %}
                                <del style="color:red"> ascenseur </del>
                            {% endif %}
                        </li>
                    </ul>
                </td>
                <td style="vertical-align: middle">
                    <ul class="list-inline">
                        <li class="list-inline-item">
                            <a href="{{ path('apartment_edit', {'id': apartment.id}) }}"><span class="badge rounded-pill bg-primary">Editer</span></a>
                        </li>
                        <li class="list-inline-item">
                            {{ include('apartment/_delete_form.html.twig') }}
                        </li>
                    </ul>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Aucun appartement disponible</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/apartment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un appartement{% endblock %}

{% block body %}
    <h1>Ajouter un appartement</h1>

    {{ form_start(form) }}
    {{ form_widget(form) }}

    <div style="float:right">
        <a href="{{ path('apartment_index') }}"><button type="button" class="btn btn-secondary"> Retour </button></a>
        <button type="submit" class="btn btn-primary"> Ajouter </button>
    </div>

    {{ form_end(form) }}

{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet"
              href="https://bootswatch.com/5/cosmo/bootstrap.min.css">
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">TestTech</a>
        </div>
    </nav>
    <div class="container">
        {% block body %}{% endblock %}
    </div>
    {% block javascripts %}{% endblock %}
    </body>
</html>